[package]
name = "lakefs"
version = "0.3.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
fuser = "0.15.1"
spdlog-rs = "0.4.3"
sqlite = "0.37.0"
toml = "0.9.2"
